### ISSUE TITLE
Configuration for 'third_party_settings' may not be null when module is being installed 

### ISSUE THREAD

**Issue by 100c1p43r** [Pronovix/swagger_ui_formatter#28] opened 2020-01-16 13:43 UTC
`SwaggerUIFileFormatter#create` contains following code:
```PHP
return new static(
      $plugin_id,
      $plugin_definition,
      $configuration['field_definition'],
      $configuration['settings'],
      $configuration['label'],
      $configuration['view_mode'],
      $configuration['third_party_settings'],
      $container->get('string_translation'),
      $container->get('logger.channel.swagger_ui_formatter')
    );
```

It happens, that module trying to install this one, won't have `third_party_settings`, just like in `devportal_api_reference`, which results in such ugly error:

`[error]  Argument 7 passed to Drupal\swagger_ui_formatter\Plugin\Field\FieldFormatter\SwaggerUIFileFormatter::__construct() must be of the type array, null given, called in /app/web/modules/contrib/swagger_ui_formatter/src/Plugin/Field/FieldFormatter/SwaggerUIFileFormatter.php on line 90`

A simple type cast would solve this problem once for all.

**Comment by mxr576** [comment] 2020-07-09 13:34
Can you provide a step by step guide which could help us to reproduce it? As I can see,  all Drupal core codes have `array` typehint on `third_party_settings`.

**Comment by mxr576** [comment] 2022-07-27 14:46
Since no feedback was provided and nobody else complained about this problem, I am closing this for now.

**Closed by mxr576** 2022-07-27 14:46 UTC
