### ISSUE TITLE
Changelog and update instructions from 2.x

### ISSUE THREAD

**Issue by mxr576** [Pronovix/swagger_ui_formatter#54] opened 2020-11-16 06:30 UTC
Create a changelog with highlight and update instructions for users of the 2.x version.

**Comment by balazswmann** [comment] 2020-11-17 09:34
I'm pasting the first draft of the 3.0 version related release notes for drupal.org. I wrote it in a HTML format because we will need to convert it to HTML anyway for drupal.org.

```
This is a new major release including Drupal 9.0.x compatibility, new features and breaking changes since 8.x-2.4!

<strong>New features</strong>

The Swagger UI library discovery and validation has been moved into a new <code>SwaggerUiLibraryDiscovery</code> service which
means that modules can now override the default Swagger UI library path and validation by decorating the service.

A new <code>hook_swagger_ui_library_directory_alter()</code> alter hook has been added specifically for the default theme which
can now also override the default library path. By doing so the theme can define or include its own supported Swagger UI library
version for a better integration and compatibility. See <code>swagger_ui_formatter.api.php</code> for more information.

<strong>Upgrade from 8.x-2.4</strong>

<ol>
<li>Make sure you have at least <strong>PHP 7.2</strong> installed. If not, please upgrade it.</li>
<li>Make sure you are using <strong>v3.32.2</strong> or a newer version from Swagger UI library. If not, please upgrade it.</li>
<li>Make sure your Swagger UI library is located in the <code>/web/libraries/swagger-ui</code> directory. If not, please move it.</li>
<li>Upgrade the Swagger UI Field Formatter module to <code>3.0</code> via Composer (<code>composer require drupal/swagger_ui_formatter:~3.0 --update-with-all-dependencies</code>).</li>
<li>Run database updates (<code>drush updb</code>) to perform the new release related update hooks.</li>
<li>Check the Drupal status report page to see wether the Swagger UI library is recognized correctly.</li>
</ol>

<strong>Changes since 8.x-2.4</strong>

<ul>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/22">#22</a> by mxr576: Drop < PHP 7.1 support</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/30">#30</a> by mxr576, balazswmann: Remove the old SVG data related functionality since from Swagger UI v3.13.4 it's bundled with the rest of the app</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/31">#31</a> by mxr576, balazswmann: Remove drupalSettings.swaggerUIFormatter.[FIELD NAME].swaggerFiles related BC from both PHP and JS</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/32">#32</a> by mxr576, balazswmann: Define correct dependency between swagger UI and its integration library</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/37">#37</a> by mxr576, balazswmann: Drupal 8.9.x and Drupal 9.0.x compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/24">#24</a> by mxr576: Add test coverage</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/42">#42</a> by balazswmann: Remove drupal-qa 2.8.0 related patch for Drupal 9 compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/38">#38</a> by mxr576, balazswmann: Move the Swagger UI library discovery to a service so the library path can be modified/decorated</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/45">#45</a> by mxr576, balazswmann: Bump the minimum supported Swagger UI library version</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/49">#49</a> by mxr576, balazswmann: Update pronovix/* dependencies to 2.11</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/54">#54</a> by mxr576, balazswmann: Changelog and update instructions from 2.x</li>
</ul>
```

**Comment by balazswmann** [comment] 2020-11-17 09:37
I have also added a `CHANGELOG.txt` file with a simple link to the drupal.org related releases page via #55

**Comment by mxr576** [comment] 2020-11-19 06:43
> hook has been added specifically for the default theme which can now also override the default library path. 

Change: hook has been added for themes so they can override the installation path of Swagger UI.

> Make sure you are using <strong>v3.32.2</strong> or a newer version from Swagger UI library. If not, please upgrade it.

Add: (This is currently the [latest security release](https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.2) of Swagger UI.)

**Comment by balazswmann** [comment] 2020-11-19 12:52
New version according to the feedback. I have also added one missing issue to the change list.

```
This is a new major release including Drupal 9.0.x compatibility, new features and breaking changes since 8.x-2.4!

<strong>New features</strong>

The Swagger UI library discovery and validation has been moved into a new <code>SwaggerUiLibraryDiscovery</code> service which means that modules can now override the default Swagger UI library path and validation by decorating the service.

A new <code>hook_swagger_ui_library_directory_alter()</code> alter hook has been added for themes so they can override the installation path of Swagger UI. By doing so the theme can define or include its own supported Swagger UI library
version for a better integration and compatibility. See <code>swagger_ui_formatter.api.php</code> for more information.

<strong>Upgrade from 8.x-2.4</strong>

<ol>
<li>Make sure you have at least <strong>PHP 7.2</strong> installed. If not, please upgrade it.</li>
<li>Make sure you are using <strong>v3.32.2</strong> or a newer version from Swagger UI library (<a href="https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.2">this is currently the latest security release</a>). If not, please upgrade it.</li>
<li>Make sure your Swagger UI library is located in the <code>/web/libraries/swagger-ui</code> directory. If not, please move it.</li>
<li>Upgrade the Swagger UI Field Formatter module to <code>3.0</code> via Composer (<code>composer require drupal/swagger_ui_formatter:~3.0 --update-with-all-dependencies</code>).</li>
<li>Run database updates (<code>drush updb</code>) to perform the new release related update hooks.</li>
<li>Check the Drupal status report page to see wether the Swagger UI library is recognized correctly.</li>
</ol>

<strong>Changes since 8.x-2.4</strong>

<ul>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/22">#22</a> by mxr576: Drop < PHP 7.1 support</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/30">#30</a> by mxr576, balazswmann: Remove the old SVG data related functionality since from Swagger UI v3.13.4 it's bundled with the rest of the app</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/31">#31</a> by mxr576, balazswmann: Remove drupalSettings.swaggerUIFormatter.[FIELD NAME].swaggerFiles related BC from both PHP and JS</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/32">#32</a> by mxr576, balazswmann: Define correct dependency between swagger UI and its integration library</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/37">#37</a> by mxr576, balazswmann: Drupal 8.9.x and Drupal 9.0.x compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/24">#24</a> by mxr576: Add test coverage</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/42">#42</a> by balazswmann: Remove drupal-qa 2.8.0 related patch for Drupal 9 compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/38">#38</a> by mxr576, balazswmann: Move the Swagger UI library discovery to a service so the library path can be modified/decorated</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/45">#45</a> by mxr576, balazswmann: Bump the minimum supported Swagger UI library version</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/49">#49</a> by mxr576, balazswmann: Update pronovix/* dependencies to 2.11</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/36">#36</a> by balazswmann: Update and correct README.md</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/54">#54</a> by mxr576, balazswmann: Changelog and update instructions from 2.x</li>
</ul>
```

**Comment by balazswmann** [comment] 2020-11-20 13:49
I run into a problem during testing the upgrade path: `drush updb` runs fine (which should rebuild the cache "theoretically") but then issuing `drush cr` complains that the `swagger_ui_formatter.swagger_ui_library_discovery` service doesn't exist.

I guess the problem is that the service is called somewhere (maybe in `hook_requirments()` or in `hook_library_info_build()`) but it's not yet registered which means that our empty post update hook doesn't rebuild the caches.

**Comment by balazswmann** [comment] 2020-11-20 13:50
I have opened a new PR #57 which fixes the problem. It looks like an empty post update hook doesn't clear the cache or it doesn't do it correctly but calling `drupal_flush_all_caches()` explicitly does the job. No more error with this approach.

**Comment by balazswmann** [comment] 2020-12-01 13:06
New version according to the latest changes/fixes.

```
This is a new major release including Drupal 9 compatibility, new features and breaking changes since 8.x-2.4!

<strong>New features</strong>

The Swagger UI library discovery and validation has been moved into a new <code>SwaggerUiLibraryDiscovery</code> service which means that modules can now override the default Swagger UI library path and validation by decorating the service.

A new <code>hook_swagger_ui_library_directory_alter()</code> alter hook has been added for themes so they can override the installation path of Swagger UI. By doing so the theme can define or include its own supported Swagger UI library
version for a better integration and compatibility. See <code>swagger_ui_formatter.api.php</code> for more information.

<strong>Upgrade from 8.x-2.4</strong>

<ol>
<li>Make sure you have at least <strong>PHP 7.2</strong> installed. If not, please upgrade it.</li>
<li>Make sure you are using <strong>v3.32.2</strong> or a newer version from Swagger UI library (<a href="https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.2">this is currently the latest security release</a>). If not, please upgrade it.</li>
<li>Make sure your Swagger UI library is located in the <code>/web/libraries/swagger-ui</code> directory. If not, please move it.</li>
<li>Upgrade the Swagger UI Field Formatter module to <code>3.0</code> via Composer (<code>composer require drupal/swagger_ui_formatter:~3.0 --update-with-all-dependencies</code>).</li>
<li>Run database updates (<code>drush updb</code>) to perform the new release related update hooks.</li>
<li>Check the Drupal status report page to see whether the Swagger UI library is recognized correctly.</li>
</ol>

<strong>Changes since 8.x-2.4</strong>

<ul>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/22">#22</a> by mxr576: Drop < PHP 7.1 support</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/30">#30</a> by mxr576, balazswmann: Remove the old SVG data related functionality since from Swagger UI v3.13.4 it's bundled with the rest of the app</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/31">#31</a> by mxr576, balazswmann: Remove drupalSettings.swaggerUIFormatter.[FIELD NAME].swaggerFiles related BC from both PHP and JS</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/32">#32</a> by mxr576, balazswmann: Define correct dependency between swagger UI and its integration library</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/37">#37</a> by mxr576, balazswmann: Drupal 8.9.x and Drupal 9.0.x compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/24">#24</a> by mxr576: Add test coverage</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/42">#42</a> by balazswmann: Remove drupal-qa 2.8.0 related patch for Drupal 9 compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/38">#38</a> by mxr576, balazswmann: Move the Swagger UI library discovery to a service so the library path can be modified/decorated</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/45">#45</a> by mxr576, balazswmann: Bump the minimum supported Swagger UI library version</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/49">#49</a> by mxr576, balazswmann: Update pronovix/* dependencies to 2.11</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/36">#36</a> by balazswmann: Update and correct README.md</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/52">#52</a> by mxr576, balazswmann: Add Drupal 9.1.x compatibility</li>
<li>Issue <a href="https://github.com/Pronovix/swagger_ui_formatter/issues/54">#54</a> by mxr576, balazswmann: Changelog and update instructions from 2.x</li>
</ul>
```

**Comment by balazswmann** [comment] 2021-02-05 08:39
Closing this, as the `8.x-3.0` version [has been released](https://www.drupal.org/project/swagger_ui_formatter/releases/8.x-3.0) on drupal.org.

**Closed by balazswmann** 2021-02-05 08:39 UTC
